### ISSUE TITLE
Overlaps the header bar

### ISSUE THREAD

**Issue by hbaileylxd** [fraylopez/adapt-breadcrumb#1]
![image](https://cloud.githubusercontent.com/assets/11558341/23993176/6dacb8a8-0a37-11e7-9c73-ff7383ef146f.png)

**Comment by fraylopez** [comment]
Hi,

What is "the header bar" exactly? What is its class name or id within the adapt view?

**Comment by hbaileylxd** [comment]
class: page-header

**Comment by fraylopez** [comment]
This is happening because 

```
#wrapper {
    width: 100%;
    margin: auto;
    overflow-x: hidden;
    padding-top: (@navigation-padding * 2) + @icon-size;

    .ie8 & {
        max-width: @ie8-max-width;
        margin: 0 auto;
    }
}
```
(at theme/src/wrapper.less)

Since this is a theme configuration it wouldn't be wise to override it from a plugin. I suggest you to handle the padding top in your theme adding the breadcrumb height (which is set to 2em in breadcrumb.less).

I'm closing this issue, thanks for posting!

**Comment by hbaileylxd** [comment]
Thanks for the advice - will do!
